schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "BG3_Lazy_Tailor"
version = "1.0.0"
name = "BG3 Lazy Tailor"
tagline = "An Outfit Refitting Tool for BG3 Modding"
maintainer = "Volno <VolnoTheArtist@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://github.com/V0ln0/BG3_Lazy_Tailor"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Pipeline", "Mesh"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
# network = "Need to sync motion-capture data to server"
files = "To load data from an internal library."
# clipboard = "Copy and paste bone transforms"
